[package]
name = "simple_image_interface"
version = "0.1.0"
description = "Simple image interface with pictures, video, and camera."
keywords = ["camera", "video", "image", "webcam"]
authors = ["scepter914 <st14.828soccer@gmail.com>"]
repository = "https://github.com/scepter914/simple-image-interface-rs"
# documentation = "https://docs.rs/simple_image_interface"
license = "MIT"
readme = "README.md"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rscam = "0.5.5"
log = "0.4.0"
simplelog = "0.10.0"
image = "0.23.14"
